name: Clojure Format Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cljfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache cljfmt
      id: cache-cljfmt
      uses: actions/cache@v4
      with:
        path: $HOME/.local/bin
        key: ${{ runner.os }}-cljfmt
        restore-keys: |
          ${{ runner.os }}-cljfmt

    - name: Add local bin directory
      run: |
        mkdir -p $HOME/.local/bin
        export PATH=$HOME/.local/bin:$PATH
        ls $HOME

    - name: Install cljfmt
      if: steps.cache-cljfmt.outputs.cache-hit != 'true'
      run: |
        curl -sLO https://raw.githubusercontent.com/rjsheperd/cljfmt/HEAD/install.sh
        chmod +x install.sh
        ./install.sh $HOME/.local/bin

    - name: Run cljfmt on .clj[sc] files
      run: |
        cljfmt check components/**/src bases/**/src projects/**/src development steps cms-exports
