name: Clojure Format Check

on: push
#  pull_request:
#    types: [opened, synchronize, reopened]

jobs:
  cljfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install cljfmt
      run: |
        mkdir -p $HOME/.local/bin
        curl -sLO https://raw.githubusercontent.com/rjsheperd/cljfmt/HEAD/install.sh
        chmod +x install.sh
        ./install.sh $HOME/.local/bin
        export PATH=$HOME/.local/bin:$PATH

    - name: Run cljfmt on .clj files
      run: cljfmt check --file-pattern '**/*.clj'

    - name: Run cljfmt on .cljs files
      run: cljfmt check --file-pattern '**/*.cljs'

    - name: Run cljfmt on .cljc files
      run: cljfmt check --file-pattern '**/*.cljc'
