name: Build and Sign JAR

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build JAR
      uses: addnab/docker-run-action@v3
      with:
        image: rjsheperd/clojure-bb-bun:latest
        options: -v ${{ github.workspace }}:/behave-polylith
        run: |
          cd /behave-polylith/projects/behave
          clj -X:download-vms :url ${{ secrets.VMS_URL }} :auth-token ${{ secrets.VMS_SECRET_TOKEN }}
          bb build-js
          bb uber

    - name: Verify assets
      run: ls -l projects/behave/target/*.jar
