name: Build and Sign JAR

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@13.0
      with:
        cli: 1.12.0

    - name: Setup Babashka
      uses: turtlequeue/setup-babashka@v1.7.0
      with:
        babashka-version: 1.3.189

   - name: Build JAR
     env:
       VMS_URL: ${{ secrets.VMS_URL }}
       VMS_AUTH_TOKEN: ${{ secrets.VMS_SECRET_TOKEN }}
     run: |
       cd projects/behave
       clj -X:download-vms :url $VMS_URL :auth-token $VMS_AUTH_TOKEN
       bb build-js
       bb uber

   # - name: Build JAR
   #   uses: addnab/docker-run-action@v3
   #   with:
   #     image: rjsheperd/clojure-bb-bun:latest
   #     options: -v ${{ github.workspace }}:/behave-polylith
   #     env:
   #       VMS_URL: ${{ secrets.VMS_URL }}
   #       VMS_AUTH_TOKEN: ${{ secrets.VMS_SECRET_TOKEN }}
   #     run: |
   #       cd /behave-polylith/projects/behave
   #       clj -X:download-vms :url $URL :auth-token $AUTH_TOKEN
   #       bb build-js
   #       git config --global --add safe.directory /behave-polylith
   #       bb uber

    - name: Verify assets
      run: ls -l projects/behave/target/*.jar
