name: Sign JAR

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sign JAR
        uses: addnab/docker-run-action@v3
        with:
          image: rjsheperd/jarsigner:latest
          options: |
            -e SM_API_KEY=${{ secrets.SM_API_KEY }} \
            -e SM_KEYPAIR=${{ secrets.SM_KEYPAIR }}
          shell: bash
          run: |
            echo $SM_API_KEY
            echo $SM_KEYPAIR
